CREATE TABLE IF NOT EXISTS product (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(20),
  category VARCHAR(20),
  manufacturer_country VARCHAR(20),
  guarantee INT,
  total_count INT,
  sales_count INT
);

TRUNCATE TABLE product;

INSERT INTO product VALUES (1, 'name', 'first-category', 'Russia', 1, 100, 10);
INSERT INTO product VALUES (2, 'name2', 'first-category', 'Russia', 1, 200, 20);
INSERT INTO product VALUES (3, 'name3', 'second-category', 'Germany', 3, 20, 10);
INSERT INTO product VALUES (4, 'name4', 'second-category', 'Germany', 3, 50, 30);
INSERT INTO product VALUES (5, 'name5', 'second-category', 'China', 1, 500, 300);
INSERT INTO product VALUES (6, 'name6', 'second-category', 'China', 1, 500, 10);
INSERT INTO product VALUES (7, 'name7', 'first-category', 'Russia', 1, 500, 123);
INSERT INTO product VALUES (8, 'name8', 'second-category', 'China', 1, 220, 22);
INSERT INTO product VALUES (9, 'name9', 'first-category', 'China', 1, 1000, 1);
INSERT INTO product VALUES (10, 'name10', 'first-category', 'Russia', 1, 10, 0);
INSERT INTO product VALUES (11, 'name11', 'first-category', 'China', 5, 500, 300);
INSERT INTO product VALUES (12, 'name12', 'second-category', 'China', 5, 500, 20);
INSERT INTO product VALUES (13, 'name13', 'second-category', 'China', 1, 100, 15);